import { Button } from '@/components/ui/button';
import { Plus, Upload, Sparkles, Trash2, Library, FileText, Loader2 } from 'lucide-react';
import { useState, useCallback, useEffect, useRef } from 'react';

import QuestionCard from "@/pages/bank_edit_page/question_card.tsx";
import AiProcessingStatus from "@/pages/bank_edit_page/ai_processing_status";

import type { Question } from '@/model/Question';
import { parseAiFile, addAllQuestions, generateAdaptiveQuestions } from '@/lib/api';
import type QuestionCreationDTO from '@/dtos/QuestionCreationDTO';
import type Tag from '@/model/Tag';
import type { AiQuestionDTO } from '@/dtos/AiQuestionDTO';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { getUserFiles } from '@/lib/api';
import type { DbFile } from '@/model/DbFile';

interface Props {
  questions: Question[];
  bankId: string;
  onUpload: (file: File) => void;
  onAttachExistingFile: (fileId: string) => void;
  linkedFiles: DbFile[];
  isImporting: boolean;
  aiRequest?: { fileId: string, operation: string } | null;
  importError: string | null;
  availableTags: Tag[];
}

export default function QuestionEditSection({ questions: initialQuestions, bankId, onUpload, onAttachExistingFile, linkedFiles, isImporting, aiRequest = null, importError, availableTags }: Props) {
  const [questions, setQuestions] = useState(initialQuestions || []);
  const [aiQuestions, setAiQuestions] = useState<Question[]>([]);
  const [newQuestion, setNewQuestion] = useState<Question | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const statusRef = useRef<HTMLDivElement>(null);

  const [processingStage, setProcessingStage] = useState<string | null>(null);

  // File Upload Dialog State
  const [isFileDialogOpen, setIsFileDialogOpen] = useState(false);
  const [libraryFiles, setLibraryFiles] = useState<DbFile[]>([]);
  const [isLoadingLibrary, setIsLoadingLibrary] = useState(false);

  useEffect(() => {
    if (isFileDialogOpen) {
      loadLibraryFiles();
    }
  }, [isFileDialogOpen]);

  const loadLibraryFiles = async () => {
    setIsLoadingLibrary(true);
    try {
      const files = await getUserFiles();
      setLibraryFiles(files);
    } catch (error) {
      console.error("Failed to load library files", error);
    } finally {
      setIsLoadingLibrary(false);
    }
  };

  const handleSelectFromLibrary = (fileId: string) => {
    onAttachExistingFile(fileId);
    setIsFileDialogOpen(false);
  };

  useEffect(() => {
    if (statusRef.current) {
      statusRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [aiQuestions, processingStage]);

  useEffect(() => {
    setQuestions(initialQuestions || []);
  }, [initialQuestions]);

  const createAiResponseHandler = () => {
    let index = 0;
    return (aiResponse: { status: string; data?: string }) => {
      if (aiResponse.status === "thinking") {
        setProcessingStage("thinking");
      }
      if (aiResponse.status === "data") {
        if (!aiResponse.data) return;
        const newAiQuestion: AiQuestionDTO = JSON.parse(aiResponse.data);
        const newQuestionTags = [];
        for (const tagName of newAiQuestion.tags) {
          const tag = availableTags.find(tag => tag.name === tagName)
          if (tag) {
            newQuestionTags.push(tag);
          }
          else if (tagName === "AI_GENERATED") {
            newQuestionTags.push({ name: tagName, id: tagName, description: "This question is generated by AI", color: "#3b82f6" });
          }
          else {
            newQuestionTags.push({ name: tagName, id: tagName, description: "", color: "#7c3aed" });
          }
        }
        const newQuestion: Question = {
          id: "AI_" + index.toString(),
          description: newAiQuestion.description,
          choices: newAiQuestion.choices,
          answer: newAiQuestion.answer,
          questionType: newAiQuestion.questionType,
          tags: newQuestionTags,
        };

        index++;
        setAiQuestions(prev => [...prev, newQuestion]);
      }
      if (aiResponse.status === "finish") {
        setProcessingStage("finish");
      }
    };
  };

  useEffect(() => {
    if (aiRequest) {
      setProcessingStage("start");
      setAiQuestions([]);
      if (aiRequest.operation === "parse") {
        parseAiFile(aiRequest.fileId, createAiResponseHandler());
      }
    }
  }, [aiRequest]);

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      onUpload(file);
    }
    // Always reset the input value so the same file can be selected again if needed
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const scrollToBottom = () => {
    window.scrollTo({
      top: document.documentElement.scrollHeight,
      behavior: 'smooth'
    });
  };

  const handleAddQuestion = () => {
    const newQuestion: Question = {
      id: 'new', // Temporary ID for new questions
      description: '',
      choices: ['', '', ''], // Start with 3 empty choices
      answer: ['0'], // Default to first choice as string
      questionType: 'SINGLE_ANSWER',
      tags: []
    };
    setNewQuestion(newQuestion);
    scrollToBottom();
  };

  const handleGenerateWithAi = () => {
    setProcessingStage("start");
    setAiQuestions([]);
    generateAdaptiveQuestions(bankId, createAiResponseHandler());
  };

  const handleAppendQuestion = useCallback((question: Question) => {
    setQuestions([...questions, question]);
  }, [questions]);

  const handleRemoveQuestion = useCallback((question: Question) => {
    if (question.id === 'new') {
      setNewQuestion(null);
      return;
    }
    if (question.id.startsWith('AI_')) {
      setAiQuestions(prev => prev.filter(q => q.id !== question.id));
      return;
    }
    setQuestions(questions.filter(q => q.id !== question.id));
  }, [questions]);

  const handleConfirmAiQuestions = async () => {
    if (aiQuestions.length === 0) return;

    try {
      const dtos: QuestionCreationDTO[] = aiQuestions.map(q => ({
        description: q.description,
        choices: q.choices,
        answer: q.answer,
        questionType: q.questionType,
        tags: q.tags?.map(tag => tag.id) || [],
      }));

      const newQuestions = await addAllQuestions(bankId, dtos);
      setQuestions([...questions, ...newQuestions]);
      setAiQuestions([]);
      setProcessingStage(null);
    } catch (error) {
      console.error("Failed to add AI questions", error);
    }
  };

  const handleDiscardAiQuestions = () => {
    setAiQuestions([]);
    setProcessingStage(null);
  };

  return (
    <div className="bg-[#0f0f10] border border-zinc-800 rounded-lg p-6 mb-6">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-xl font-semibold">Questions ({questions.length || 0})</h2>
        <div className="flex space-x-2">
          <Button
            variant="outline"
            className="border-zinc-700 text-zinc-300 bg-[#151518] hover:bg-[#1a1a1c]"
            onClick={() => setIsFileDialogOpen(true)}
            disabled={isImporting}
          >
            <Upload className="w-4 h-4 mr-2" />
            {isImporting ? 'Uploading...' : 'Upload File'}
          </Button>
          <input
            ref={fileInputRef}
            type="file"
            onChange={handleFileChange}
            className="hidden"
          />

          <Button
            variant="outline"
            className="border-zinc-700 text-zinc-300 bg-[#151518] hover:bg-[#1a1a1c]"
            onClick={handleAddQuestion}
          >
            <Plus className="w-4 h-4 mr-2" />
            Add Question
          </Button>
          <Button
            variant="outline"
            className="border-violet-600 text-violet-300 bg-violet-950/30 hover:bg-violet-900/40"
            onClick={handleGenerateWithAi}
            disabled={!!processingStage}
          >
            <Sparkles className="w-4 h-4 mr-2" />
            AI Generate
          </Button>
        </div>
      </div>

      {/* Import Error Display */}
      {importError && (
        <div className="mb-4 bg-red-900/20 border border-red-700 rounded-lg p-4">
          <p className="text-red-200">{importError}</p>
        </div>
      )}

      {/* Questions List */}
      <div className="space-y-4">
        {questions.map((q, index) =>
          <QuestionCard key={q.id} questionProp={q} bankId={bankId} index={index} isEditingProp={false}
            appendQuestion={handleAppendQuestion} removeQuestion={handleRemoveQuestion} availableTags={availableTags}
            updateQuestionHandler={(updatedQuestion) => {
              setQuestions(prev => prev.map(item => item.id === updatedQuestion.id ? updatedQuestion : item));
            }}
          />
        )}
        {newQuestion && <QuestionCard questionProp={newQuestion} bankId={bankId} index={0} isEditingProp={true}
          appendQuestion={handleAppendQuestion} removeQuestion={handleRemoveQuestion} availableTags={availableTags} />}
      </div>

      {/* Add Question Button at Bottom */}
      {!newQuestion && !processingStage &&
        <div className="mt-6 border-2 border-dashed border-zinc-700 rounded-lg p-4 flex justify-center">
          <Button
            variant="outline"
            className="border-zinc-600 text-zinc-300 bg-[#151518] hover:bg-[#1a1a1c]"
            onClick={handleAddQuestion}
          >
            <Plus className="w-4 h-4 mr-2" />
            Add New Question
          </Button>
        </div>}

      {processingStage && (
        <div className="mt-6 border-2 border-dashed border-zinc-700 rounded-lg p-4 flex flex-col justify-center">
          <div className="space-y-4">
            {aiQuestions.map((q, index) =>
              <QuestionCard key={q.id} questionProp={q} bankId={bankId} index={index} isEditingProp={false}
                appendQuestion={handleAppendQuestion} removeQuestion={handleRemoveQuestion} availableTags={availableTags} />
            )}
          </div>
          <div ref={statusRef} className="mt-12">
            <AiProcessingStatus stage={processingStage} />
            {processingStage === "finish" && (
              <div className="flex justify-center mt-4 space-x-2">
                <Button
                  variant="outline"
                  className="border-zinc-700 text-zinc-300 bg-[#151518] hover:bg-[#1a1a1c]"
                  onClick={handleDiscardAiQuestions}
                >
                  <Trash2 className="w-4 h-4 mr-2" />
                  Discard All
                </Button>
                <Button
                  className="bg-violet-600 hover:bg-violet-700 text-white"
                  onClick={handleConfirmAiQuestions}
                >
                  <Plus className="w-4 h-4 mr-2" />
                  Add All {aiQuestions.length} Questions to Bank
                </Button>
              </div>
            )}
          </div>
        </div>
      )}

      <Dialog open={isFileDialogOpen} onOpenChange={setIsFileDialogOpen}>
        <DialogContent className="bg-[#151518] border-zinc-800 text-white sm:max-w-xl">
          <DialogHeader>
            <DialogTitle>Add File to Question Bank</DialogTitle>
            <DialogDescription className="text-zinc-400">
              Upload a new file or choose an existing one from your library.
            </DialogDescription>
          </DialogHeader>

          <div className="grid gap-6 py-4">
            <div className="flex flex-col gap-3">
              <h3 className="text-sm font-medium text-zinc-300">Upload New</h3>
              <Button
                variant="outline"
                className="w-full border-zinc-700 border-dashed bg-[#0f0f10] hover:bg-zinc-900 h-20 flex flex-col gap-2"
                onClick={() => {
                  fileInputRef.current?.click();
                  setIsFileDialogOpen(false);
                }}
              >
                <Upload className="w-5 h-5 text-zinc-500" />
                <span className="text-xs text-zinc-400">Click to upload from computer</span>
              </Button>
            </div>

            <div className="flex flex-col gap-3">
              <h3 className="text-sm font-medium text-zinc-300">Choose from Library</h3>
              <div className="max-h-[300px] overflow-y-auto pr-2 flex flex-col gap-2">
                {isLoadingLibrary ? (
                  <div className="flex items-center justify-center py-8 text-zinc-500">
                    <Loader2 className="w-6 h-6 animate-spin mr-2" />
                    <span>Loading library...</span>
                  </div>
                ) : libraryFiles.filter(f => !linkedFiles.some(lf => lf.id === f.id)).length > 0 ? (
                  libraryFiles
                    .filter(f => !linkedFiles.some(lf => lf.id === f.id))
                    .map(file => (
                      <div
                        key={file.id}
                        onClick={() => handleSelectFromLibrary(file.id)}
                        className="flex items-center justify-between p-3 rounded-lg border border-zinc-800 bg-[#0f0f10] hover:border-violet-600/50 hover:bg-violet-900/10 cursor-pointer transition-all group"
                      >
                        <div className="flex items-center min-w-0">
                          <FileText className="w-4 h-4 mr-3 text-zinc-500 group-hover:text-violet-400" />
                          <div className="min-w-0">
                            <p className="text-sm font-medium truncate">{file.fileName}</p>
                            <p className="text-[10px] text-zinc-500">{new Date(file.uploadDate).toLocaleDateString()}</p>
                          </div>
                        </div>
                        <Library className="w-4 h-4 text-zinc-700 group-hover:text-violet-500 opacity-0 group-hover:opacity-100 transition-opacity" />
                      </div>
                    ))
                ) : (
                  <div className="text-center py-8 text-zinc-500 text-sm">
                    No files found in your library.
                  </div>
                )}
              </div>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
